export interface Acronym {
  acronym: string;
  definition: string;
}

export const DEFAULT_ACRONYMS: Acronym[] = [
  { acronym: "ABM", definition: "AIR BATTLE MANAGER" },
  { acronym: "ACE", definition: "AGILE COMBAT EMPLOYMENT" },
  { acronym: "AD", definition: "ACTIVE DUTY" },
  { acronym: "ADCON", definition: "ADMINISTRATIVE CONTROL" },
  { acronym: "AFE", definition: "AIRCREW FLIGHT EQUIPMENT" },
  { acronym: "AFFORGEN", definition: "AIR FORCE FORCE GENERATION" },
  { acronym: "AFI", definition: "AIR FORCE INSTRUCTION" },
  { acronym: "AFMAN", definition: "AIR FORCE MANUAL" },
  { acronym: "AFSC", definition: "AIR FORCE SPECIALTY CODE" },
  { acronym: "AFSO21", definition: "AIR FORCE SMART OPERATIONS FOR THE 21ST CENTURY" },
  { acronym: "AGE", definition: "AEROSPACE GROUND EQUIPMENT" },
  { acronym: "AGR", definition: "ACTIVE GUARD RESERVE" },
  { acronym: "AI", definition: "ARTIFICIAL INTELLIGENCE" },
  { acronym: "ALQ", definition: "AIRMAN LEADERSHIP QUALITY" },
  { acronym: "ALS", definition: "AIRMAN LEADERSHIP SCHOOL" },
  { acronym: "AOC", definition: "AIR OPERATIONS CENTER" },
  { acronym: "AOR", definition: "AREA OF RESPONSIBILITY" },
  { acronym: "APF", definition: "APPROPRIATED FUNDS" },
  { acronym: "ART", definition: "AIR RESERVE TECHNICIAN" },
  { acronym: "AT", definition: "ANNUAL TOUR" },
  { acronym: "ATC", definition: "AIR TRAFFIC CONTROL" },
  { acronym: "ATO", definition: "AIR TASKING ORDER" },
  { acronym: "BMT", definition: "BASIC MILITARY TRAINING" },
  { acronym: "BNR", definition: "BY NAME REQUEST" },
  { acronym: "BTZ", definition: "BELOW-THE-ZONE" },
  { acronym: "C2", definition: "COMMAND AND CONTROL" },
  { acronym: "C4ISR", definition: "COMMAND, CONTROL, COMMUNICATIONS, COMPUTERS, INTELLIGENCE, SURVEILLANCE AND RECONNAISSANCE" },
  { acronym: "CAOC", definition: "COMBINED AIR OPERATIONS CENTER" },
  { acronym: "CAS", definition: "CLOSE AIR SUPPORT" },
  { acronym: "CAT", definition: "CRISIS ACTION TEAM" },
  { acronym: "CATM", definition: "COMBAT ARMS TRAINING AND MAINTENANCE" },
  { acronym: "CBRN", definition: "CHEMICAL, BIOLOGICAL, RADIOLOGICAL, NUCLEAR" },
  { acronym: "CBT", definition: "COMPUTER BASED TRAINING" },
  { acronym: "CCAF", definition: "COMMUNITY COLLEGE OF THE AIR FORCE" },
  { acronym: "CCIP", definition: "COMMANDER'S INSPECTION PROGRAM" },
  { acronym: "CDI", definition: "COMMANDER DIRECTED INVESTIGATION" },
  { acronym: "CFETP", definition: "CAREER FIELD EDUCATION AND TRAINING PLAN" },
  { acronym: "CFM", definition: "CAREER FIELD MANAGER" },
  { acronym: "CLA", definition: "CHIEF MASTER SERGEANT LEADERSHIP ACADEMY" },
  { acronym: "CLC", definition: "CHIEF MASTER SERGEANT LEADERSHIP COURSE" },
  { acronym: "COA", definition: "COURSE OF ACTION" },
  { acronym: "CODEL", definition: "CONGRESSIONAL DELEGATION" },
  { acronym: "CONOPS", definition: "CONCEPT OF OPERATIONS" },
  { acronym: "CONUS", definition: "CONTINENTAL UNITED STATES" },
  { acronym: "COOP", definition: "CONTINUITY OF OPERATIONS" },
  { acronym: "CPI", definition: "CONTINUOUS PROCESS IMPROVEMENT" },
  { acronym: "CPR", definition: "CARDIOPULMONARY RESUSCITATION" },
  { acronym: "CSAR", definition: "COMBAT SEARCH AND RESCUE" },
  { acronym: "CUI", definition: "CONTROLLED UNCLASSIFIED INFORMATION" },
  { acronym: "DAFI", definition: "DEPARTMENT OF THE AIR FORCE INSTRUCTION" },
  { acronym: "DAFMAN", definition: "DEPARTMENT OF THE AIR FORCE MANUAL" },
  { acronym: "DEOCS", definition: "DEFENSE EQUAL OPPORTUNITY CLIMATE SURVEY" },
  { acronym: "DG", definition: "DISTINGUISHED GRADUATE" },
  { acronym: "DHA", definition: "DEFENSE HEALTH AGENCY" },
  { acronym: "DSG", definition: "DRILL STATUS GUARDSMAN" },
  { acronym: "DV", definition: "DISTINGUISHED VISITOR" },
  { acronym: "EKIA", definition: "ENEMY KILLED IN ACTION" },
  { acronym: "EOC", definition: "EMERGENCY OPERATIONS CENTER" },
  { acronym: "EOD", definition: "EXPLOSIVE ORDNANCE DISPOSAL" },
  { acronym: "EOY", definition: "END OF YEAR" },
  { acronym: "EPB", definition: "ENLISTED PERFORMANCE BRIEF" },
  { acronym: "EW", definition: "ELECTRONIC WARFARE" },
  { acronym: "FAM", definition: "FUNCTIONAL AREA MANAGER" },
  { acronym: "FHP", definition: "FLYING HOUR PROGRAM" },
  { acronym: "FMC", definition: "FULLY MISSION CAPABLE" },
  { acronym: "FOB", definition: "FORWARD OPERATING BASE" },
  { acronym: "FOC", definition: "FULL OPERATIONAL CAPABILITY" },
  { acronym: "FOL", definition: "FORWARD OPERATING LOCATION" },
  { acronym: "FPCON", definition: "FORCE PROTECTION CONDITIONS" },
  { acronym: "FTEC", definition: "FIRST TERM ENLISTED COURSE" },
  { acronym: "FTU", definition: "FORMAL TRAINING UNIT" },
  { acronym: "GPA", definition: "GRADE POINT AVERAGE" },
  { acronym: "GPS", definition: "GLOBAL POSITIONING SYSTEM" },
  { acronym: "GSU", definition: "GEOGRAPHICALLY SEPARATED UNIT" },
  { acronym: "GTC", definition: "GOVERNMENT TRAVEL CARD" },
  { acronym: "IDT", definition: "INACTIVE DUTY TRAINING" },
  { acronym: "IDE", definition: "INTERMEDIATE DEVELOPMENTAL EDUCATION" },
  { acronym: "IED", definition: "IMPROVISED EXPLOSIVE DEVICE" },
  { acronym: "IMA", definition: "INDIVIDUAL MOBILIZATION AUGMENTEE" },
  { acronym: "IOC", definition: "INITIAL OPERATIONAL CAPABILITY" },
  { acronym: "IP", definition: "INSTRUCTOR PILOT" },
  { acronym: "ISR", definition: "INTELLIGENCE, SURVEILLANCE, AND RECONNAISSANCE" },
  { acronym: "IT", definition: "INFORMATION TECHNOLOGY" },
  { acronym: "JADC2", definition: "JOINT ALL DOMAIN COMMAND AND CONTROL" },
  { acronym: "JROTC", definition: "JUNIOR RESERVE OFFICER TRAINING CORPS" },
  { acronym: "KIA", definition: "KILLED IN ACTION" },
  { acronym: "LOE", definition: "LINE OF EFFORT" },
  { acronym: "MCA", definition: "MULTI-CAPABLE AIRMEN" },
  { acronym: "MDS", definition: "MISSION DESIGN SERIES" },
  { acronym: "MILCON", definition: "MILITARY CONSTRUCTION" },
  { acronym: "MILPDS", definition: "MILITARY PERSONNEL DATA SYSTEM" },
  { acronym: "MOA", definition: "MEMORANDUM OF AGREEMENT" },
  { acronym: "MOU", definition: "MEMORANDUM OF UNDERSTANDING" },
  { acronym: "MTF", definition: "MEDICAL TREATMENT FACILITY" },
  { acronym: "MWR", definition: "MORALE, WELFARE, AND RECREATION" },
  { acronym: "MX", definition: "MAINTENANCE" },
  { acronym: "NC3", definition: "NUCLEAR COMMAND, CONTROL, AND COMMUNICATIONS" },
  { acronym: "NCOA", definition: "NONCOMMISSIONED OFFICER ACADEMY" },
  { acronym: "NCR", definition: "NATIONAL CAPITAL REGION" },
  { acronym: "NDAA", definition: "NATIONAL DEFENSE AUTHORIZATION ACT" },
  { acronym: "NDS", definition: "NATIONAL DEFENSE STRATEGY" },
  { acronym: "NEO", definition: "NONCOMBATANT EVACUATION OPERATION" },
  { acronym: "NIPR", definition: "NON-SECURE INTERNET PROTOCOL ROUTER" },
  { acronym: "NMC", definition: "NON MISSION CAPABLE" },
  { acronym: "O&M", definition: "OPERATIONS AND MAINTENANCE" },
  { acronym: "OCO", definition: "OVERSEAS CONTINGENCY OPERATIONS" },
  { acronym: "OCONUS", definition: "OUTSIDE CONTINENTAL UNITED STATES" },
  { acronym: "OJT", definition: "ON THE JOB TRAINING" },
  { acronym: "OPLAN", definition: "OPERATIONS PLAN" },
  { acronym: "OPSEC", definition: "OPERATIONAL SECURITY" },
  { acronym: "OTS", definition: "OFFICER TRAINING SCHOOL" },
  { acronym: "PCS", definition: "PERMANENT CHANGE OF STATION" },
  { acronym: "PDE", definition: "PRIMARY DEVELOPMENTAL EDUCATION" },
  { acronym: "PFA", definition: "PHYSICAL FITNESS ASSESSMENT" },
  { acronym: "PME", definition: "PROFESSIONAL MILITARY EDUCATION" },
  { acronym: "POC", definition: "POINT OF CONTACT" },
  { acronym: "PT", definition: "PHYSICAL TRAINING" },
  { acronym: "QA", definition: "QUALITY ASSURANCE" },
  { acronym: "QoL", definition: "QUALITY OF LIFE" },
  { acronym: "ROE", definition: "RULES OF ENGAGEMENT" },
  { acronym: "ROTC", definition: "RESERVE OFFICER TRAINING CORPS" },
  { acronym: "RPA", definition: "REMOTELY PILOTED AIRCRAFT" },
  { acronym: "SAPR", definition: "SEXUAL ASSAULT PREVENTION AND RESPONSE" },
  { acronym: "SCIF", definition: "SENSITIVE COMPARTMENTED INFORMATION FACILITY" },
  { acronym: "SDE", definition: "SENIOR DEVELOPMENTAL EDUCATION" },
  { acronym: "SERE", definition: "SURVIVAL, EVASION, RESISTANCE, ESCAPE" },
  { acronym: "SIPR", definition: "SECRET INTERNET PROTOCOL ROUTER" },
  { acronym: "SME", definition: "SUBJECT MATTER EXPERT" },
  { acronym: "SNCOA", definition: "SENIOR NONCOMMISSIONED OFFICER ACADEMY" },
  { acronym: "SOF", definition: "SPECIAL OPERATIONS FORCES" },
  { acronym: "SOP", definition: "STANDARD OPERATING PROCEDURE" },
  { acronym: "SOS", definition: "SQUADRON OFFICER SCHOOL" },
  { acronym: "STEM", definition: "SCIENCE, TECHNOLOGY, ENGINEERING, AND MATHEMATICS" },
  { acronym: "TACP", definition: "TACTICAL AIR CONTROL PARTY" },
  { acronym: "TCCC", definition: "TACTICAL COMBAT CASUALTY CARE" },
  { acronym: "TDY", definition: "TEMPORARY DUTY" },
  { acronym: "TFI", definition: "TOTAL FORCE INTEGRATION" },
  { acronym: "TR", definition: "TRADITIONAL RESERVIST" },
  { acronym: "TS", definition: "TOP SECRET" },
  { acronym: "TTP", definition: "TACTICS, TECHNIQUES, AND PROCEDURES" },
  { acronym: "UCI", definition: "UNIT COMPLIANCE INSPECTION" },
  { acronym: "UCMJ", definition: "UNIFORM CODE OF MILITARY JUSTICE" },
  { acronym: "UEI", definition: "UNIT EFFECTIVENESS INSPECTION" },
  { acronym: "UTA", definition: "UNIT TRAINING ASSEMBLY" },
  { acronym: "UTC", definition: "UNIT TYPE CODE" },
  { acronym: "UXO", definition: "UNEXPLODED ORDNANCE" },
  { acronym: "WRM", definition: "WAR RESERVE MATERIEL" },
  { acronym: "XAB", definition: "EXPEDITIONARY AIRBASE" },
];

export function formatAcronymsList(acronyms: Acronym[]): string {
  return acronyms.map((a) => `${a.acronym} = ${a.definition}`).join("\n");
}

