import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy Policy for My EPBuddy - Learn how we handle your data securely and transparently.",
};

export default function PrivacyPolicyPage() {
  return (
    <article className="prose prose-neutral dark:prose-invert max-w-none">
      <h1>Privacy Policy</h1>
      <p className="text-muted-foreground">
        Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
      </p>

      <section className="mt-8">
        <h2>Overview</h2>
        <p>
          My EPBuddy (&quot;we,&quot; &quot;our,&quot; or &quot;the Service&quot;) is an independent personal productivity 
          tool designed to help Air Force service members track accomplishments and draft EPB narrative statements.
        </p>
        <div className="bg-muted/50 border rounded-lg p-4 my-4">
          <p className="font-semibold text-foreground mb-2">Important Disclaimer</p>
          <p className="text-sm mb-0">
            My EPBuddy is <strong>not affiliated with, endorsed by, or connected to</strong> the United States 
            Air Force, Department of Defense, or any other U.S. Government entity. This is an independent 
            tool for personal productivity use.
          </p>
        </div>
      </section>

      <section className="mt-8">
        <h2>Information We Collect</h2>
        
        <h3>Account Information</h3>
        <p>When you create an account, we collect:</p>
        <ul>
          <li>Email address (for authentication)</li>
          <li>Display name (optional)</li>
          <li>Rank information (for statement generation customization)</li>
        </ul>

        <h3>Accomplishment Data</h3>
        <p>
          You voluntarily provide accomplishment entries including actions, impacts, and metrics. 
          This data is stored securely and is only accessible by you and any team members you 
          explicitly authorize.
        </p>

        <h3>Generated Content</h3>
        <p>
          Narrative statements generated by the Service are stored in your account for your reference. 
          You maintain full ownership of all content you create.
        </p>

        <h3>API Keys</h3>
        <p>
          If you choose to use your own AI provider API keys, they are encrypted before storage 
          and are never logged or shared.
        </p>
      </section>

      <section className="mt-8">
        <h2>How We Use Your Information</h2>
        <p>We use your information solely to:</p>
        <ul>
          <li>Provide and improve the Service functionality</li>
          <li>Generate AI-powered narrative statements based on your input</li>
          <li>Enable team collaboration features you explicitly opt into</li>
          <li>Send important service-related communications</li>
        </ul>
        <p>
          <strong>We do not:</strong>
        </p>
        <ul>
          <li>Sell your personal information</li>
          <li>Share your data with third parties for marketing</li>
          <li>Use your accomplishment data to train AI models</li>
          <li>Access your data for any purpose other than providing the Service</li>
        </ul>
      </section>

      <section className="mt-8">
        <h2>Data Security</h2>
        <p>We implement industry-standard security measures including:</p>
        <ul>
          <li>Encryption in transit (TLS 1.3) and at rest</li>
          <li>Secure, encrypted storage for API keys</li>
          <li>Row-level security policies in our database</li>
          <li>Regular security audits and updates</li>
          <li>HTTPS enforcement with HSTS</li>
        </ul>
      </section>

      <section className="mt-8">
        <h2>Third-Party Services</h2>
        <p>We use the following third-party services:</p>
        <ul>
          <li>
            <strong>Supabase:</strong> Database and authentication (hosted in the United States)
          </li>
          <li>
            <strong>AI Providers:</strong> OpenAI, Anthropic, or Google (when you use their APIs 
            for statement generation). Your accomplishment data is sent to these services only 
            when you explicitly request statement generation.
          </li>
          <li>
            <strong>Vercel:</strong> Hosting and analytics
          </li>
        </ul>
        <p>
          Each of these services has their own privacy policies. We recommend reviewing them 
          if you have concerns about their data handling practices.
        </p>
      </section>

      <section className="mt-8">
        <h2>Data Retention</h2>
        <p>
          Your data is retained as long as your account is active. You may request deletion 
          of your account and all associated data at any time by contacting us.
        </p>
      </section>

      <section className="mt-8">
        <h2>Your Rights</h2>
        <p>You have the right to:</p>
        <ul>
          <li>Access your personal data</li>
          <li>Export your accomplishment data</li>
          <li>Request correction of inaccurate data</li>
          <li>Request deletion of your account and data</li>
          <li>Opt out of non-essential communications</li>
        </ul>
      </section>

      <section className="mt-8">
        <h2>Children&apos;s Privacy</h2>
        <p>
          This Service is not intended for individuals under 18 years of age. We do not 
          knowingly collect personal information from children.
        </p>
      </section>

      <section className="mt-8">
        <h2>Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. We will notify users of 
          significant changes via email or through the Service.
        </p>
      </section>

      <section className="mt-8">
        <h2>Contact Us</h2>
        <p>
          If you have questions about this Privacy Policy or our data practices, please 
          contact us through the Support page within the application.
        </p>
      </section>
    </article>
  );
}




